version: "1.0"
info:
  model: int-scaffold
packages:
- name: Seren_GH_1201Project
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
